### ISSUE TITLE
アプリためとくところ

### ISSUE THREAD

**Issue by naoyuki2** [naoyuki2/AppEcho#167]
立てられているアプリが少ないからここにためとく

![image](https://github.com/naoyuki2/AppEcho/assets/135786069/4c6f4945-44b9-4d18-9eee-63ccbaeebb7d)

**Comment by naoyuki2** [comment]
`youtube`
アプリアイコン
`https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/7f/f7/ee/7ff7eec0-5849-8171-1c52-af465ce6285a/logo_youtube_color-0-1x_U007emarketing-0-0-0-6-0-0-0-85-220-0.png/512x512bb.jpg`
app store
`https://apps.apple.com/jp/app/youtube/id544007664?uo=4`
play store
`https://play.google.com/store/apps/details?id=com.google.android.youtube`

**Comment by wolf-2013** [comment]
Instagram
アプリアイコン
https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/a4/fc/9c/a4fc9cf1-619d-728b-2af2-bd32777b8b0a/Prod-0-0-1x_U007emarketing-0-7-0-85-220.png/512x512bb.jpg
app store
https://apps.apple.com/jp/app/instagram/id389801252?uo=4
play store
https://play.google.com/store/apps/details?id=com.instagram.android

**Comment by wolf-2013** [comment]
LINE
https://is1-ssl.mzstatic.com/image/thumb/Purple221/v4/d9/c0/1f/d9c01fb8-30b8-b7c8-06d2-75f91eff74e6/AppIcon-0-0-1x_U007emarketing-0-5-0-0-sRGB-85-220.png/512x512bb.jpg
app store
https://apps.apple.com/jp/app/line/id443904275?uo=4
play store
https://play.google.com/store/apps/details?id=jp.naver.line.android

**Comment by wolf-2013** [comment]
discode
https://is1-ssl.mzstatic.com/image/thumb/Purple221/v4/0c/28/f0/0c28f089-4d5a-3388-1acd-21ffa9ded1c6/AppIcon-0-0-1x_U007epad-0-0-85-220.png/512x512bb.jpg
app store
https://apps.apple.com/jp/app/discord-%25E4%25B8%2580%25E7%25B7%2592%25E3%2581%25AB%25E3%2581%2597%25E3%2582%2583%25E3%2581%25B9%25E3%2581%25A3%25E3%2581%25A6%25E9%2581%258A%25E3%2582%2593%25E3%2581%25A7%25E9%259B%2586%25E3%2581%25BE%25E3%2582%258D%25E3%2581%2586/id985746746?uo=4
play store
https://play.google.com/store/apps/details?id=com.discord

**Comment by naoyuki2** [comment]
アプリ投稿機能できたのでクローズ
