### ISSUE TITLE
Headerの修正

### ISSUE THREAD

**Issue by naoyuki2** [naoyuki2/AppEcho#33]
## ゴール

下の条件をすべて満たしている

## 詳細情報

- 編集するファイル：
　　　　`src/components/Header.php`
　　　　`src/css/Header.css`

## 条件

- [ ] Headerの虫眼鏡アイコンをタップでアプリ検索画面に遷移できる
- [x] Headerのロゴをタップでアプリ一覧画面に遷移できる
- [ ] Headerと他の要素が重なっていない(position:fixedからposition:stickyに変更すればいけそう)

現在はアプリのアイコンと重なってしまっている。
<img width="300" src="https://github.com/naoyuki2/AppEcho/assets/135786069/214c10f2-b2c7-4deb-a410-b448be0b3f0b" />

## 各種リンク

- [デプロイURL](https://aso2201030.verse.jp/AppEcho/src/pages/AppList.php)
- [position:stickyのドキュメント](https://developer.mozilla.org/ja/docs/Web/CSS/position)

## 備考

Headerと他の要素が重なっていないことを検証し、その様子のキャプチャをPRに貼り付けてほしいです

**Comment by aespakari7** [comment]
<img width="1512" alt="スクリーンショット 2024-05-14 10 15 51" src="https://github.com/naoyuki2/AppEcho/assets/147119919/e9fca630-8033-43be-a912-126fc6d20eb3">
修正しました
